
version: '3.3'
services:

  service:
    build: .
    restart: always
    image: chat-service-image
    container_name: chat-service-container
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - backend

  database:
    image: postgres:10-alpine
    restart: always
    container_name: chat-postgres-container
    environment:
      - "POSTGRES_USER=chat_admin"
      - "POSTGRES_PASSWORD=123qwe"
      - "POSTGRES_DB=chat_db"
    networks:
      - backend
    ports:
    - "5432:5432"

networks:
  backend:
