
logging.level.root: DEBUG
server.port: 9090
spring:
  profiles: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: test
    password: test

---

logging.level.root: INFO
server.port: 8080
spring:
  jpa:
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL93Dialect
        current_session_context_class: thread
        jdbc:
          lob:
            non_contextual_creation: true

  datasource:
    initialization-mode: always
    username: chat_admin
    password: 123qwe
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://chat-postgres-container/chat_db
